const express = require("express");
const router = express.Router();
const ctrl = require("../controllers/userController");
const { upload, cloudinaryUpload } = require("../middlewares/upload");
const { requireAuth, requireOwnerParam, requireOwnerId } = require("../middlewares/auth");
const userOffers = require("./userOffers");
const userPortfolio = require("./userPortfolio");
const svcCtrl = require("../controllers/serviceRequestController");
const userPayments = require("./userPayments");
const userSocialLinks = require("./userSocialLinks");
const socialCtrl = require("../controllers/socialLinkController");
const analyticsCtrl = require("../controllers/analyticsController");

router.get("/", requireAuth, ctrl.list);
router.post("/", requireAuth, ctrl.create);
router.get("/me", requireAuth, ctrl.getMe);
router.get("/public/list", ctrl.getPublicUsers);
router.get("/:username", ctrl.getByUsername);
router.get("/:username/profile", ctrl.getProfile);
router.get("/:username/storage", requireAuth, requireOwnerParam("username"), ctrl.getStorageUsage);
router.patch("/:username", requireAuth, requireOwnerParam("username"), ctrl.updateByUsername);
router.delete("/:username", requireAuth, requireOwnerParam("username"), ctrl.removeByUsername);
router.post("/:username/avatar", requireAuth, requireOwnerParam("username"), upload.single("avatar"), cloudinaryUpload, ctrl.setAvatarFromReq);
router.get("/me", requireAuth, ctrl.getMe);
router.get("/id/:id", requireAuth, requireOwnerId("id"), ctrl.getById);
router.patch("/id/:id", requireAuth, requireOwnerId("id"), ctrl.updateById);
router.post("/id/:id/avatar", requireAuth, requireOwnerId("id"), upload.single("avatar"), cloudinaryUpload, ctrl.setAvatarFromReqById);
router.post("/id/:id/email/otp/send", requireAuth, requireOwnerId("id"), ctrl.sendEmailUpdateOtpById);
router.post("/id/:id/email/otp/verify", requireAuth, requireOwnerId("id"), ctrl.verifyEmailUpdateOtpById);
router.use("/:username/offers", userOffers);
router.use("/:username/portfolio", userPortfolio);
router.get("/:username/service-requests", requireAuth, requireOwnerParam("username"), svcCtrl.listForUser);
router.get("/:username/service-requests/:id", requireAuth, requireOwnerParam("username"), svcCtrl.getForUser);
router.patch("/:username/service-requests/:id", requireAuth, requireOwnerParam("username"), svcCtrl.updateForUser);
router.delete("/:username/service-requests/:id", requireAuth, requireOwnerParam("username"), svcCtrl.removeForUser);
router.use("/:username/payments", userPayments);
router.use("/:username/social-links", userSocialLinks);
router.get("/id/:id/social-links", requireAuth, requireOwnerId("id"), socialCtrl.listForUserById);
router.post("/id/:id/social-links", requireAuth, requireOwnerId("id"), socialCtrl.createForUserById);
router.get("/id/:id/social-links/:linkId", requireAuth, requireOwnerId("id"), socialCtrl.getForUserById);
router.patch("/id/:id/social-links/:linkId", requireAuth, requireOwnerId("id"), socialCtrl.updateForUserById);
router.delete("/id/:id/social-links/:linkId", requireAuth, requireOwnerId("id"), socialCtrl.removeForUserById);
router.post("/:username/analytics/view", analyticsCtrl.trackView);
router.post("/:username/analytics/click", analyticsCtrl.trackClick);
router.get("/:username/analytics/summary", requireAuth, requireOwnerParam("username"), analyticsCtrl.getSummary);

module.exports = router;
